flysystem:
    storages:
        contact.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/pictures/pictures/contact'
        project.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/pictures/pictures/project'