parameters:
  env(APP_ENV): 'dev'
  env(APP_SECRET): '6a8b52cfd6cbbccdebb01422ab0ed6e4'
  env(DATABASE_URL): 'mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.0.32&charset=utf8mb4'
  env(JWT_SECRET_KEY): '%kernel.project_dir%/config/jwt/private.pem'
  env(JWT_PUBLIC_KEY): '%kernel.project_dir%/config/jwt/public.pem'
  env(JWT_PASSPHRASE): 'c0e96d0e6dd39e8e8cb93d9163f71719efe6e8ebcf929063af1aee07dbfcec57'
  env(CORS_ALLOW_ORIGIN): '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
  env(MAILER_DSN): 'yourMailerDSN'
  env(MAIL_ADDRESS): 'your@email.tld'
  env(MESSENGER_TRANSPORT_DSN): 'doctrine://default?auto_setup=true'
  env(SCHEDULER_TRANSPORT_DSN): 'in-memory://'
  env(ENCRYPTION_KEY): 'yourEncryptionKey'

  mailer.dsn: '%env(MAILER_DSN)%'